package ds_Group_Project;
import java.util.Vector;

public class Order {
	private String orderID;
	private Vector<CartItem> item;
	private DateTime timestamp;
	private Customer cust;
	private double total;
	private String orderStatus;
	
	//Constructors
	public Order() {
		orderID = " ";
		item = new Vector<>();
		timestamp = new DateTime();
		cust = new Customer();
		total = 0.0;
		orderStatus = "Processing";
	}
	
	public Order(String id, Vector<CartItem> i, DateTime dt, Customer c, double t, String status) {
		orderID = id;
		item = i;
		timestamp = dt;
		cust = c;
		total = t;
		orderStatus = status;
	}
	
	public Order(Order o) {
		orderID = o.orderID;
		item = new Vector<>(o.item);
		timestamp = o.timestamp;
		cust = o.cust;
		total = o.total;
		orderStatus = o.orderStatus;
	}
	
	//Accessors and Mutators
	public String GetOrderID() { return orderID; }
	public void SetOrderID(String id) { orderID = id; }
	public Vector<CartItem> GetCartItem() { return item; }
	public void SetCartItem(Vector<CartItem> i) { item = i; }
	public DateTime GetDateTime() { return timestamp; }
	public void SetDateTime(DateTime dt) { timestamp = dt; }
	public Customer GetCustomer() { return cust; }
	public void SetCustomer(Customer c) { cust = c; }
	public double GetTotal() { return total; }
	public void SetTotal(double t) { total = t; }
	public String GetOrderStatus() { return orderStatus; }
	public void SetOrderStatus(String status) { orderStatus = status; }
	
	//order id is generated by checking a vector of existing orders if the order id already exists 
	public void generateOrderID(Vector<Order> existingorders) {
		String id;
		while(true) {
			int randNum = (int)((Math.random() * 9000) + 1000);
			id = "ORD" + randNum;
			boolean exist = false;
			
			for(Order o : existingorders) {
				if(String.valueOf(o.GetOrderID()).equals(id)) {
					exist = true;
					break;
				}
			}
			if(!exist) break;
		}
		orderID = id;
	}
	
	//updates the order status
	public void UpdateOrderStatus(String newStatus) {
		switch(newStatus) {	
			case "Confirmed":
				orderStatus = "Confirmed";
				break;
				
			case "Shipped":
				orderStatus = "Shipped";
				break;
				
			case "Delivered":
				orderStatus = "Delivered";
				break;
				
			case "Cancelled":
				orderStatus = "Cancelled";
				break;
				
			case "Returned":
				orderStatus = "Returned";
				break;
				
			default:
				System.out.println("Invalid order status");
		}
	}

	//prints the order
	//AI used to assist in writing toString in this format
	@Override
	public String toString() {
		String items = "";
		
		for(CartItem i : item) {
			items += i.toString() + "\n";
		}
		
		String order = "\nOrder ID: " + orderID + 
					   "\nCustomer: " + cust.getFName() + " " + cust.getLName() +
					   "\nTimestamp: " + timestamp + 
					   "\nOrder Status: " + orderStatus + 
					   "\nItems: \n"  + items + "Total: $" + total ;
		return order;
	}
}
